### ISSUE TITLE
如何开始呢？

### ISSUE THREAD

**Issue by whhxmwhh** [sswsproject/ssws#1]
能介绍详细些吗？
heluk我试着注册不成功过一次。

**Comment by sswsproject** [comment]
我自问已经写得尽可能周到了，但如果你对python没有什么概念，可能确实会有困难。我无法再完整的写一遍部署方法，尤其是针对heroku的部署。但你可以提出究竟遇到哪个具体问题，我可以在我的经验之内想办法给出我的答案。注册不成功有可能是heroku的网站有部分也是被墙的，可能需要先利用其它办法访问到它的 id.heroku.com 才行。

**Comment by sswsproject** [comment]
since there is no update for a while...
